services:
  nginx:
    container_name: brutalisme
    image: nginx:1-alpine
    networks:
      - npm
    volumes:
      - ./.:/usr/share/nginx/html
  
networks:
  default:
    external: true
    name: npm
